### ISSUE TITLE
Pages aren't refreshed ;)

### ISSUE THREAD

**Issue by anaelChardan** [tamarasaurus/immo-feed#30]
**Describe the bug**
When we remove results pages are never updated (it will be empty if we remove everything)

**To Reproduce**
1. Go to a page
2. Remove all houses
4. See the page is now empty and it will never change

**Expected behavior**
Pages to be filled

**Screenshots**
<img width="1663" alt="screen shot 2018-07-07 at 12 00 51 pm" src="https://user-images.githubusercontent.com/6115681/42409643-ba55c752-81dd-11e8-9e91-6b3946c2be6f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 67.0.3396.99

**Additional context**

**Comment by tamarasaurus** [comment]
Hey thanks for reporting this bug! 😉  I will fix it in the upcoming 1.2.0 release - https://github.com/tamarasaurus/immo-feed/pull/28

**Comment by anaelChardan** [comment]
Thanks Tam' :)

**Comment by tamarasaurus** [comment]
Hey @anaelChardan, this issue has been fixed and released :slightly_smiling_face: - https://github.com/tamarasaurus/immo-feed/releases/tag/1.2.0
